Repository MovingBlocks/DestinationSol, pull requests merged in 2018-10, with the labels that each got.

#317 fix regression introduced by #281: red target crosshair now draws again
  engine/src/main/java/org/destinationsol/game/SolGame.java
Labels: Bugfix

#314 Update gradle to 4.10.2
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: Enhancement-architectural

#319 After dying, you won't respawn with your previous save.
  engine/src/main/java/org/destinationsol/game/SolGame.java
Labels: Bugfix

#322 Dagger 2 minimum
  config/gradle/common.gradle
  desktop/build.gradle
  desktop/src/main/java/org/destinationsol/desktop/SolDesktop.java
  engine/build.gradle
  engine/src/main/java/org/destinationsol/CommonDrawer.java
  engine/src/main/java/org/destinationsol/ModuleManager.java
  engine/src/main/java/org/destinationsol/SolApplication.java
  engine/src/main/java/org/destinationsol/assets/audio/OggMusicManager.java
  engine/src/main/java/org/destinationsol/assets/audio/OggSoundManager.java
  engine/src/main/java/org/destinationsol/di/AppModule.java
  engine/src/main/java/org/destinationsol/di/GameModule.java
  engine/src/main/java/org/destinationsol/di/LootModule.java
  engine/src/main/java/org/destinationsol/di/Qualifier/Mobile.java
  engine/src/main/java/org/destinationsol/di/Qualifier/NewGame.java
  engine/src/main/java/org/destinationsol/di/Qualifier/OnPauseUpdate.java
  engine/src/main/java/org/destinationsol/di/Qualifier/OnUpdate.java
  engine/src/main/java/org/destinationsol/di/Qualifier/ShipName.java
  engine/src/main/java/org/destinationsol/di/Qualifier/Tutorial.java
  engine/src/main/java/org/destinationsol/di/SystemsModule.java
  engine/src/main/java/org/destinationsol/di/components/SolApplicationComponent.java
  engine/src/main/java/org/destinationsol/di/components/SolGameComponent.java
  engine/src/main/java/org/destinationsol/di/components/SolObjectLootComponent.java
  engine/src/main/java/org/destinationsol/di/scope/GameScope.java
  engine/src/main/java/org/destinationsol/di/scope/SolObjectScope.java
  engine/src/main/java/org/destinationsol/files/HullConfigManager.java
  engine/src/main/java/org/destinationsol/game/GridDrawer.java
  engine/src/main/java/org/destinationsol/game/MapDrawer.java
  engine/src/main/java/org/destinationsol/game/PlayerCreator.java
  engine/src/main/java/org/destinationsol/game/SolGame.java
  engine/src/main/java/org/destinationsol/game/StarPort.java
  engine/src/main/java/org/destinationsol/game/chunk/ChunkProvider.java
  engine/src/main/java/org/destinationsol/game/item/Gun.java
  engine/src/main/java/org/destinationsol/game/item/ItemManager.java
  engine/src/main/java/org/destinationsol/game/item/Loot.java
  engine/src/main/java/org/destinationsol/game/screens/GameScreens.java
  engine/src/main/java/org/destinationsol/game/screens/MainGameScreen.java
  engine/src/main/java/org/destinationsol/game/screens/ShipMixedControl.java
  engine/src/main/java/org/destinationsol/menu/MenuScreens.java
  engine/src/main/java/org/destinationsol/ui/SolInputManager.java
Labels: Enhancement-architectural, WIP

#329 Extract ResolutionProvider from GameOptions
  engine/src/main/java/org/destinationsol/GameOptions.java
  engine/src/main/java/org/destinationsol/menu/Resolution.java
  engine/src/main/java/org/destinationsol/menu/ResolutionProvider.java
  engine/src/test/java/org/destinationsol/menu/ResolutionProviderTest.java
Labels: Enhancement-code quality
